### ISSUE TITLE
#write command doesn't output header properties

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd#112]
## Problem description
When using 
`#write test.csv overhead_line,underground_line:latitude,longitude,phases,nominal_voltage`
The output doesn't contain header properties
~~~
id,class,name,latitude,longitude,phases,nominal_voltage
19,overhead_line,"line_632-645",,,BCN,+0 V
20,overhead_line,"line_645-646",,,BCN,+0 V
21,overhead_line,"line_630-632",,,ABCN,+0 V
22,overhead_line,"line_632-6321",,,ABCN,+0 V
23,overhead_line,"line_6321-671",,,ABCN,+0 V
24,overhead_line,"line_671-680",,,ABCN,+0 V
25,overhead_line,"line_671-684",,,ACN,+0 V
26,overhead_line,"line_684-611",,,CN,+0 V
27,underground_line,"line_684-652",,,AN,+0 V
28,underground_line,"line_692-675",,,ABC,+0 V
29,overhead_line,"line_632-633",,,ABCN,+0 V
~~~
[issue_112.zip](https://github.com/arras-energy/gridlabd/files/12820761/issue_112.zip)

**Comment by dchassin** [comment]
The correct syntax is `CLASS1,CLASS2,...:PROP1,PROP1,...`

**Comment by dchassin** [comment]
It looks like it cannot process header properties.  That needs to be supported so things like lat/lon can be written.
