### ISSUE TITLE
Unable to use macros within python environment

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd#20]
## Problem description

When using the format 

main.py : 
~~~
import gridlabd
gridlabd.command("test.glm")
gridlabd.start("wait")
~~~

and test.glm contains a macro such as `#weather get`

this error occurs: 
~~~
aivanovalocal@PC99458 sce_poles % gridlabd main_cardinal_network.py
/bin/bash: gridlabd/gridlabd-weather: No such file or directory
ERROR    [INIT] : GldMain::subcommand(format='%s/gridlabd-%s',...): command 'gridlabd/gridlabd-weather get CA-Chino_Airport.tmy3
' returns code 127
main_cardinal_poles.glm(16): #weather macro is not recognized
FATAL    [INIT] : shutdown after command line rejected
~~~

**Comment by dchassin** [comment]
Do it work if you use the full command macro, e.g., `#gridlabd weather get...`?

**Comment by dchassin** [comment]
Problem 1: the macro expansion of `#weather` is not doing anything, while `#gridlabd weather` works ok.

Problem 2: the command line syntax `gridlabd file.py` does not do anything, while `gridlabd python file.py` works ok.
